### ISSUE TITLE
`all` target reports error when no citations present

### ISSUE THREAD

**Issue by btoschek** [btoschek/hsc-template#4]
When running `make all` without having any citations in the document, the task executes fine but returns an error affecting following tasks. This makes `make full` not clean up the directory of all files created during compilation, which breaks its functionality.

**Comment by HannesLueer** [comment]
I stumbled upon the problem yesterday as well. But I wasn't sure if this might be desired behavior (the log file might be helpful for other LaTeX errors). My solution was to change full to this: 

```
full: 
    make -i all 
    make clean
```
	
This fixes `make full` but does not fix the error of a manual call of `make all`

**Comment by btoschek** [comment]
To me, this sounds a bit counter-productive. With your proposal we would just shift the issue to another part of the code. I'm currently trying solutions including non-conditional execution with `&` instead of `&&`, but wasn't able to get something up and running yet.

To be honest, I really don't like that the `Makefile` is calling itself (through `make`). There should be another way to do this.
